apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: hello-k8s
        image: 638173936794.dkr.ecr.us-west-2.amazonaws.com/hello-k8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "mysql://hellouser:hellopass@mysql:3306/hello"
        - name: GREETING
          value: "Hello k8s from Minikube!"
