apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-dbcreation-script
data: 
  mysql_usermgmt.sql: |-
    USE hello;
    CREATE TABLE messages (
      id INT AUTO_INCREMENT PRIMARY KEY,
      message VARCHAR(255)
    );
    INSERT INTO messages (message)
    VALUES
      ('Greetings from planet kube'),
      ('The number you have dialed is not in service.');    
