apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-store-csi-driver-secret-access
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: hellok8s
    meta.helm.sh/release-namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]