{{- if regexMatch ".*1" .Values.environment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-dbcreation-script
data: 
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS hello;
    CREATE DATABASE hello;
    CREATE USER 'hellouser'@'%' IDENTIFIED BY 'hellopass';
    GRANT ALL PRIVILEGES ON hello.* TO 'hellouser'@'%';
    USE hello;
    CREATE TABLE messages (
      id INT AUTO_INCREMENT PRIMARY KEY,
      message VARCHAR(255)
    );
    INSERT INTO messages (message)
    VALUES
      ('Greetings from planet kube'),
      ('The number you have dialed is not in service.');    
{{- end }}
