{{- if regexMatch ".*eks.*" .Values.environment }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:{{ .Values.aws_region }}:{{ .Values.aws_account_id }}:secret:my-secret-0nKwa6"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "hello-password"
          - path: "username"
            objectAlias: "hello-username"
  secretObjects:
    - secretName: hello-secret
      type: Opaque
      data:
        - objectName: "hello-password"
          key: "hello-password"
        - objectName: "hello-username"
          key: "hello-username"
{{- end }}