{{- if regexMatch ".*eks.*" .Values.environment }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws_account_id }}:role/CSISecretsManagerRole"
{{- end }}