{{- if regexMatch ".*eks.*" .Values.environment }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:{{ .Values.aws_region }}:{{ .Values.aws_account_id }}:secret:my-secret-0nKwa6"
        objectType: "secretsmanager"
{{- end }}