# templates/storageclass.yaml
{{- if regexMatch ".*eks.*" .Values.environment }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: hellok8s
    meta.helm.sh/release-namespace: default
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
{{- end }}
