name: Build & Push to Minikube

on: 
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t hello-k8s:latest ./stage01 -f ./stage01/Dockerfile
        docker save hello-k8s:latest > hello-k8s-latest.tar

    - name: Save the Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-k8s
        path: |
          ./hello-k8s-latest.tar

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-k8s

    - name: Load Docker image into minikube
      run: |
        eval $(minikube docker-env)  # Ensures docker commands use Minikube's Docker
        echo "After minikube eval: $DOCKER_HOST"
        docker load -i hello-k8s-latest.tar
        echo "After load: $DOCKER_HOST"

    - name: Deploy to Minikube
      run: |
        kubectl apply -f stage01/k8s/deployment.yaml