name: Test secrets with environment

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      env:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - stage
        - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-to-assume: "arn:aws:iam::638173936794:role/${{ inputs.env }}K8sCrawlerGithubRole"

    - name: Retrieve and Iterate Over Secrets
      run: |
        scripts/print_secrets.sh
